local:
  service: Disk
  root: <%= Rails.root.join("storage_dev") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

production:
  service: Disk
  root: <%= Rails.root.join("storage") %>